title: "Le Marbre Fraternel"
description: "L'Équation du Bonheur • La Physique de l'Éthique"
remote_theme: jekyll/minima # Thème de base léger et propre

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets
