title: "Le Marbre Fraternel"
description: "L'Équation du Bonheur • La Physique de l'Éthique"
author: "Damien NZEYIMANA"
# ID Google Analytics intégré ici
google_analytics: G-DD9PSM34WE
keywords: "Webnovel, Webtoon, Roman Web, Web-série, Hard Science-Fiction, Pandéthique, Physique de l'éthique, Ontologie, Éthique computationnelle, Biologie synthétique, Nanotechnologie moléculaire, IA Alignement, Prospective, Nanorobotique essaimique, World-building, Transmédia, Écosystème narratif, Expérience immersive, Philosophie futuriste, Spiritualité technologique, Religion du futur, Théologie, Métaphysique, Sagesse, Éveil de conscience, Transhumanisme, Intelligence artificielle, Anticipation"
lang: fr_FR

# Configuration du thème
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Gestion du menu de navigation (Header)
header_pages:
  - index.md
  - PANDETHIQUE.md
  - LIVRE-BLANC.md
  - REJOINDRE.md
  - CONTACT.md

# Compression des styles pour la performance
sass:
  style: :compressed

# Inclusion des ressources graphiques
include:
  - assets
